# Generated by Django 5.0.6 on 2024-06-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='content',
            new_name='text',
        ),
    ]
