# Generated by Django 5.0.6 on 2024-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('platform', models.CharField(max_length=100, verbose_name='Платформа')),
                ('ocenka', models.TextField(verbose_name='Оценка игры')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
            ],
        ),
    ]
